### ISSUE TITLE
Incorrect binary search tree picture

### ISSUE THREAD

**Issue by stardustmeg** [AlreadyBored/basic-js-ds#23]
According to the structure of a Binary search tree the right node is supposed to have a greater value than the parent one, so in this case the node must have a value greater than 5.
![image](https://github.com/AlreadyBored/basic-js-ds/assets/146496794/6b91d9c9-1843-4dca-9dfa-d8f4f7c90c6c)

Here's the picture for replacement
![image](https://github.com/AlreadyBored/basic-js-ds/assets/146496794/c273fc36-2a2a-405d-b6c5-3dd8addec195)

**Comment by AlreadyBored** [comment]
Corresponding PR merged
