### ISSUE TITLE
update tests for "Remove from list test cases" task

### ISSUE THREAD

**Issue by kot-ig** [AlreadyBored/basic-js-ds#6]
Would you mind to add some additional test cases to the [Remove from list](https://github.com/AlreadyBored/basic-js-ds/blob/master/README.md#remove-from-list) task:

 - list with double `k` value (for example: initial `[1, 2, 3, 3, 4, 5]`, expected `[1, 2, 4, 5]`)

 - list with `k` at the end (for example: initial  `[1, 2, 3]`,  expected `[1, 2]` )

**Comment by AlreadyBored** [comment]
Hi! Your PRs are welcome :)

**Comment by kot-ig** [comment]
Thanks
PR has been created
[feat: add test cases for "Remove from list" task](https://github.com/AlreadyBored/basic-js-ds/pull/7)
